# Config file for automatic testing at travis-ci.org

# Containerized builds
sudo: false

language: python

python:
  - "3.5.0"
  - "3.4"
  - "3.3"
  - "2.7"
  - "pypy"

install:
  - pip install -U .
  - pip install -U marshmallow --pre
  - npm install -g swagger-tools
  - pip install -r dev-requirements.txt

before_script:
  - flake8 .

script: py.test
